[workspace]
resolver = "2"
members = ["api", "config", "core"]
exclude = ["arceos"]

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = [
    "Azure-stars <Azure_stars@126.com>",
    "Yuekai Jia <equation618@gmail.com>",
]
homepage = "https://github.com/arceos-org/arceos"
repository = "https://github.com/arceos-org/starry-next"

[workspace.dependencies]
axfeat = { path = "arceos/api/axfeat", features = [
    "alloc-slab",
    "page-alloc-4g",
    "fs",
    "fp_simd",
    "irq",
    "lwext4_rs",
    "multitask",
    "net",
    "sched_fifo",
    "smp",
] }

axalloc = { path = "arceos/modules/axalloc" }
axconfig = { path = "arceos/modules/axconfig" }
axfs-ng = { path = "arceos/modules/axfs-ng" }
axhal = { path = "arceos/modules/axhal", features = ["uspace", "rtc"] }
axlog = { path = "arceos/modules/axlog" }
axmm = { path = "arceos/modules/axmm" }
axnet = { path = "arceos/modules/axnet" }
axruntime = { path = "arceos/modules/axruntime" }
axsync = { path = "arceos/modules/axsync" }
axtask = { path = "arceos/modules/axtask", features = ["task-ext"] }

axfs-ng-vfs = { git = "https://github.com/Starry-Mix-THU/axfs-ng-vfs", rev = "f488cdf" }
axprocess = { git = "https://github.com/Starry-Mix-THU/axprocess.git", rev = "1666809" }
axsignal = { git = "https://github.com/Starry-Mix-THU/axsignal.git", rev = "65d2c6e" }

axerrno = "0.1"
bitflags = "2.6"
cfg-if = "1.0"
extern-trait = "0.2"
linkme = "0.3.33"
linux-raw-sys = { version = "0.9.3", default-features = false, features = [
    "no_std",
    "general",
    "net",
    "prctl",
    "system",
] }
memory_addr = "0.4"
scope-local = "0.1"
spin = "0.9"

starry-config = { path = "./config" }
starry-core = { path = "./core" }
starry-api = { path = "./api" }

[package]
name = "starry"
version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true

[features]
lwext4_rs = ["axfeat/lwext4_rs"]

[dependencies]
axfeat.workspace = true

axconfig.workspace = true
axfs-ng.workspace = true
axhal.workspace = true
axlog.workspace = true
axruntime.workspace = true
axsync.workspace = true
axtask.workspace = true

axprocess.workspace = true
axsignal.workspace = true

axerrno.workspace = true
linkme.workspace = true
linux-raw-sys.workspace = true

starry-config.workspace = true
starry-core.workspace = true
starry-api.workspace = true

shlex = { version = "1.3.0", default-features = false }
syscalls = { git = "https://github.com/jasonwhite/syscalls.git", rev = "92624de", default-features = false }

[patch.'https://github.com/oscomp/arceos.git']
axhal = { path = "arceos/modules/axhal" }

[package.metadata.vendor-filter]
platforms = ["riscv64gc-unknown-none-elf", "loongarch64-unknown-none"]
