[package]
name = "starry-config"
version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
cfg-if.workspace = true
