on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - uses: Swatinem/rust-cache@v2
        with:
          cache-targets: false

      - run: cargo install cargo-binutils
      - uses: arceos-org/setup-musl@v1
        with:
          arch: riscv64
      - uses: arceos-org/setup-musl@v1
        with:
          arch: loongarch64

      - name: Build
        run: make all

  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4
        with:
          path: source
          submodules: recursive

      - name: Checkout oscomp repository
        run: |
          git clone "${{ secrets.OSCOMP_REPO }}" oscomp
          cd oscomp
          git config user.name ${{ secrets.OSCOMP_USER_NAME }}
          git config user.email ${{ secrets.OSCOMP_USER_EMAIL }}

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2025-01-18
          components: rust-src, llvm-tools
          targets: riscv64gc-unknown-none-elf, loongarch64-unknown-none

      - uses: Swatinem/rust-cache@v2
        with:
          cache-targets: false

      - name: Prepare dependencies
        env:
          RUSTUP_TOOLCHAIN: nightly-2025-01-18
        run: |
          cd source
          cargo install cargo-vendor-filterer
          cargo vendor-filterer > cargo_config.toml
          cargo install --root . axconfig-gen

      - name: Push to oscomp repo
        run: |
          rsync -a --exclude='.git' --delete source/ oscomp/
          cd oscomp
          git add -A
          git commit -m ${{ github.ref_name }}.${{ github.sha }}
          git push
