on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [riscv64, loongarch64]
        include:
          - arch: riscv64
            target: riscv64gc-unknown-none-elf
          - arch: loongarch64
            target: loongarch64-unknown-none-softfloat
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - uses: Swatinem/rust-cache@v2
        with:
          cache-targets: false

      - run: cargo install cargo-binutils
      - uses: arceos-org/setup-musl@v1
        with:
          arch: ${{ matrix.arch }}

      - name: Clippy
        run: |
          cargo clippy --target ${{ matrix.target }} -F qemu -- -D warnings

      - name: Build
        run: make ARCH=${{ matrix.arch }} build
